version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data_sahara:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: sahara
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp-content:/root/www/sahara/wp-content
    ports:
      - "8001:80"
    restart: always
    environment:
      VIRTUAL_HOST: sahara2.tmy.io
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: sahara
volumes:
  db_data_sahara: {}

#networks:
  #default:
    #external:
      #name: nginx-proxy
